// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_hashed_password.sql

package database

import (
	"context"
)

const getHashedPasswordByUser = `-- name: GetHashedPasswordByUser :one
SELECT hashed_password FROM users 
  WHERE ($1 = email)
`

func (q *Queries) GetHashedPasswordByUser(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getHashedPasswordByUser, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
